# ----------------------- #
#      Main Configs       #
# ----------------------- #

baseurl: /onet
title: Workshop on Offer Networks
email: onetworkshop/at/gmail.com
institute: The Global Brain Institute
description: 

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: pretty

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

social:
  - title: twitter
    url: https://twitter.com/GB_Institute
  - title: facebook
    url: https://www.facebook.com/GlobalBrainInstitute
  - title: youtube
    url: https://www.youtube.com/user/GlobalBrainInstitute
  - title: www
    url: http://www.GlobalBrainInstitute.org
